In [ ]:
"""
Numeric types
All right, you know the basics of how tensors work. But we haven’t touched on the
numeric types you can store in a Tensor. The dtype argument to tensor constructors
(that is, functions such as tensor, zeros, and ones) specifies the numerical data type
that will be contained in the tensor. The data type specifies the possible values that the
tensor can hold (integers versus floating-point numbers) and the number of bytes per
value.4 The dtype argument is deliberately similar to the standard NumPy argument
of the same name. Here’s a list of the possible values for the dtype argument:
􀂃 torch.float32 or torch.float—32-bit floating-point
􀂃 torch.float64 or torch.double—64-bit, double-precision floating-point
􀂃 torch.float16 or torch.half—16-bit, half-precision floating-point
􀂃 torch.int8—Signed 8-bit integers
􀂃 torch.uint8—Unsigned 8-bit integers
􀂃 torch.int16 or torch.short —Signed 16-bit integers
􀂃 torch.int32 or torch.int   —Signed 32-bit integers
􀂃 torch.int64 or torch.long  —Signed 64-bit integers

Each of torch.float, torch.double, and so on has a corresponding concrete class of
torch.FloatTensor, torch.DoubleTensor, and so on. The class for torch.int8 is
torch.CharTensor, and the class for torch.uint8 is torch.ByteTensor. torch.Tensor
is an alias for torch.FloatTensor. The default data type is 32-bit floating-point.
"""

In [64]:
short_points.dtype

torch.int16

In [65]:
import torch 

duble_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [66]:
"""
You can also cast the output of a tensor-creation function to the right type by using the
corresponding casting method, such as
"""
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [67]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [68]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [69]:
# or the more convenient to method:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(torch.short)

In [70]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [71]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [72]:
"""
Under the hood, type and to perform the same type check-and-convert-if-needed
operation, but the to method can take additional arguments.
You can always cast a tensor of one type as a tensor of another type by using the
type method:
"""
points = torch.randn(10, 2)
short_points = points.type(torch.short)
short_points

tensor([[ 0,  0],
        [ 3,  0],
        [ 0,  0],
        [ 0,  0],
        [-1,  1],
        [ 0,  0],
        [ 1,  0],
        [ 1,  0],
        [ 0,  0],
        [ 0,  0]], dtype=torch.int16)

In [73]:
points

tensor([[ 0.4182, -0.0825],
        [ 3.3700,  0.3775],
        [-0.3348, -0.9279],
        [ 0.8068,  0.8039],
        [-1.6143,  1.5556],
        [-0.0844, -0.7385],
        [ 1.6965,  0.2266],
        [ 1.3784, -0.4868],
        [-0.8881,  0.7786],
        [ 0.7528, -0.0645]])

In [74]:
points.dtype

torch.float32

In [75]:
"""
Indexing tensors
You’ve seen that points[0] returns a tensor containing the 2D point at the first row of
the tensor. What if you need to obtain a tensor that contains all points but the first?
That task is easy when you use range indexing notation, the same kind that applies to
standard Python lists:
"""
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [76]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [77]:
some_list[1:4]

[1, 2, 3]

In [78]:
some_list[1:]

[1, 2, 3, 4, 5]

In [79]:
some_list[:4]

[0, 1, 2, 3]

In [80]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [81]:
some_list[1:4:2]

[1, 3]

In [82]:
"""
To achieve your goal, you can use the same notation for PyTorch tensors, with the
added benefit that as in NumPy and in other Python scientific libraries, we can use
range indexing for each dimension of the tensor:
"""
points[1:]

tensor([[ 3.3700,  0.3775],
        [-0.3348, -0.9279],
        [ 0.8068,  0.8039],
        [-1.6143,  1.5556],
        [-0.0844, -0.7385],
        [ 1.6965,  0.2266],
        [ 1.3784, -0.4868],
        [-0.8881,  0.7786],
        [ 0.7528, -0.0645]])

In [83]:
points[1:, :]

tensor([[ 3.3700,  0.3775],
        [-0.3348, -0.9279],
        [ 0.8068,  0.8039],
        [-1.6143,  1.5556],
        [-0.0844, -0.7385],
        [ 1.6965,  0.2266],
        [ 1.3784, -0.4868],
        [-0.8881,  0.7786],
        [ 0.7528, -0.0645]])

In [84]:
points[1:, 0]

tensor([ 3.3700, -0.3348,  0.8068, -1.6143, -0.0844,  1.6965,  1.3784, -0.8881,
         0.7528])

In [85]:
float(points[0])

ValueError: only one element tensors can be converted to Python scalars

In [ ]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy

In [3]:
"""
NumPy interoperability
we strongly encourage you to get familiar with NumPy due to its ubiquity in the
Python data science ecosystem. PyTorch tensors can be converted to NumPy arrays
and vice versa efficiently. By doing so, you can leverage the huge swath of functionality
in the wider Python ecosystem that has built up around the NumPy array type. This zero-copy interoperability with NumPy arrays is due to the storage system that works
with the Python buffer protocol.
To get a NumPy array out of your points tensor, call :
"""
import torch
import numpy

points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [87]:
# PyTorch Tensor
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
"""
Above numpy array :

which returns a NumPy multidimensional array of the right size, shape, and numerical
type. Interestingly, the returned array shares an underlying buffer with the tensor
storage. As a result, the numpy method can be executed effectively at essentially no cost
as long as the data sits in CPU RAM, and modifying the NumPy array leads to a change
in the originating tensor.
If the tensor is allocated on the GPU, PyTorch makes a copy of the content of the
tensor into a NumPy array allocated on the CPU.
Conversely, you can obtain a PyTorch tensor from a NumPy array this way
"""
points = torch.from_numpy(points_np)
points

# which uses the same buffer-sharing strategy.

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
"""
Serializing tensors
Creating a tensor on the fly is all well and good, but if the data inside it is of any value
to you, you want to save it to a file and load it back at some point. After all, you don’t
want to have to retrain a model from scratch every time you start running your program!
PyTorch uses pickle under the hood to serialize the tensor object, as well as
dedicated serialization code for the storage. Here’s how you can save your points tensor
to a ourpoints.t file:

Error! C:\Users\jay_s\PyTorch\2. Numeric Types\ourpoints.t is not UTF-8 encoded
Saving disabled.
See Console for more details.
"""

In [19]:
from __future__ import unicode_literals
import sys
import math
from importlib import reload

if sys.version[0] == '2':
    reload(sys)
    sys.setdefaultencoding("utf-8")

In [20]:
points = torch.from_numpy(points_np)
torch.save(points, 'outpoints.t')



In [31]:
with open('ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [36]:
# Loading your points back is similarly a one-liner:
points = torch.load('ourpoints.t')
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
with open('ourpoints.t', 'rb') as f:
    points = torch.load(f)

In [44]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
import h5py

f = h5py.File('ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

OSError: Unable to create file (unable to truncate a file which is already open)

In [10]:
"""
Here, data wasn’t loaded when the file was opened or the data set was required.
Rather, data stayed on disk until you requested the second and last rows in the data
set. At that point, h5py accessed those two columns and returned a NumPy array-like
object encapsulating that region in that data set that behaves like a NumPy array and
has the same API.
"""

f = h5py.File('ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[1:]


In [11]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [12]:
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [13]:
dset[1:]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [14]:
dset[:]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [15]:
last_points = torch.from_numpy(dset[1:])
f.close()

In [16]:
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [19]:
points_gpu = points.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
"""
This code returns a new tensor that has the same numerical data but is stored in the
RAM of the GPU rather than in regular system RAM.
Now that the data is stored locally on the GPU, you start to see speedups when performing
mathematical operations on the tensor. Also, the class of this new GPU-backed
tensor changes to torch.cuda.FloatTensor. (Given the starting type of torch.Float-
Tensor; the corresponding set of torch.cuda.DoubleTensor and so on exists.) In
almost all cases, CPU- and GPU-based tensors expose the same user-facing API, making it much 
easier to write code that is agnostic to where the heavy number-crunching process
is running.
In case your machine has more than one GPU, you can decide which GPU to allocate
the tensor to by passing a zero-based integer identifying the GPU on the
machine:
"""

In [ ]:
points_gpu = points.to(device='cuda:0')

In [ ]:
# Tensors on GPU.png

In [ ]:
# To move the tensor back to the CPU, you need to provide a cpu argument to the to method:
points_cpu = points_gpu.to(device='cpu')