In [1]:
"""
First, the vast majority of operations on and between tensors are available under
the torch module and can also be called as methods of a tensor object. The transpose
function that you encountered earlier, for example, can be used from the torch
module
"""
import torch

a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [8]:
a_t = a.transpose(0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
"""
No difference exists between the two forms, which can be used interchangeably.
A caveat, though: a small number of operations exist only as methods of the tensor
object. They’re recognizable by the trailing underscore in their name, such as zero_,
which indicates that the method operates in-place by modifying the input instead of
creating a new output tensor and returning it. The zero_ method, for example, zeros
out all the elements of the input. Any method without the trailing underscore leaves
the source tensor unchanged and returns a new tensor:
"""
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
"""
Earlier, we mentioned the online docs11, which are exhaustive and well organized with
the tensor operations divided into groups:
􀂃 Creation ops—Functions for constructing a tensor, such as ones and from_numpy
􀂃 Indexing, slicing, joining, and mutating ops—Functions for changing the shape,
stride, or content of a tensor, such as transpose
􀂃 Math ops—Functions for manipulating the content of the tensor through computations:
    – Pointwise ops—Functions for obtaining a new tensor by applying a function to
      each element independently, such as abs and cos
    – Reduction ops—Functions for computing aggregate values by iterating through
      tensors, such as mean, std, and norm Comparison ops—Functions for evaluating numerical predicates over tensors,
      such as equal and max
    – Spectral ops—Functions for transforming in and operating in the frequency
      domain, such as stft and hamming_window
    – Other ops—Special functions operating on vectors, such as cross, or matrices,
      such as trace
    – BLAS and LAPACK ops—Functions that follow the BLAS (Basic Linear Algebra
      Subprograms) specification for scalar, vector-vector, matrix-vector, and
      matrix-matrix operations
      
􀂃 Random sampling ops—Functions for generating values by drawing randomly
from probability distributions, such as randn and normal
􀂃 Serialization ops—Functions for saving and loading tensors, such as load and
save
􀂃 Parallelism ops—Functions for controlling the number of threads for parallel
CPU execution, such as set_num_threads
"""