In [ ]:
"""  
Tensor Operations
"""

In [2]:
# Arithmetic Operations
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
c = a + b  # tensor([5, 7, 9])

c

tensor([5, 7, 9])

In [6]:
# Element-wise multiplication
d = a * b  # tensor([4, 10, 18])
d

tensor([ 4, 10, 18])

In [8]:
# Matrix Multiplication

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
z = torch.matmul(x, y)  # tensor([[19, 22], [43, 50]])
z

tensor([[19, 22],
        [43, 50]])