"""  
Tensor Operations
"""

In [1]:
# Arithmetic Operations
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
c = a + b  # tensor([5, 7, 9])

c

tensor([5, 7, 9])

In [2]:
# Element-wise multiplication
d = a * b  # tensor([4, 10, 18])
d

tensor([ 4, 10, 18])

In [3]:
# Matrix Multiplication

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
z = torch.matmul(x, y)  # tensor([[19, 22], [43, 50]])
z

tensor([[19, 22],
        [43, 50]])

In [4]:
# Define two 1D tensors (vectors)
x = torch.tensor([1, 2, 3])  # Shape: (3,)
y = torch.tensor([4, 5, 6])  # Shape: (3,)

# Perform dot product
z = torch.matmul(x, y)

print(z)

tensor(32)


In [5]:
# Define two 3D tensors (batches of matrices)
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape: 2x2x2
y = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])  # Shape: 2x2x2

# Perform batched matrix multiplication
z = torch.matmul(x, y)

print(z)

tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])
