In [3]:
# Figure 1.1 The change in perspective brought by deep learning
# Figure 1.2 Static graph for a simple computation corresponding to a single neuron
# Figure 1.3 Dynamic graph for a simple computation corresponding to a single neuron
# Figure 1.4 Basic high-level structure of a PyTorch project, with data loading, training, and deployment to production
# Figure 2.1 A deep neural network learns how to transform an input representation to an output representation.
# Figure 2.2 Tensors are the building blocks for representing data in PyTorch
# Figure 2.3 Python object (boxed) numeric values versus tensor (unboxed array) numeric values
import torch

points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

points

tensor([1., 4., 2., 1., 3., 5.])

In [3]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

In [2]:
# to get the coordinates of the first point
points[0]

tensor(1.)

In [5]:
float(points[0])

1.0

In [7]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [8]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [9]:
# Here, you passed a list of lists to the constructor. You can ask the tensor about its
# shape
points.shape

torch.Size([3, 2])

In [10]:
# You could also use zeros or ones to initialize the tensor, providing the size as a tuple:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
# Now you can access an individual element in the tensor by using two indices:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [12]:
points[0, 1]

tensor(4.)

In [13]:
# You can also access the first element in the tensor as you did before to get the 2D coordinates of
# the first point:
points[0]

tensor([1., 4.])

In [14]:
"""
Values are allocated in contiguous chunks of memory, managed by torch.Storage
instances. A storage is a one-dimensional array of numerical data, such as a contiguous
block of memory containing numbers of a given type, perhaps a float or int32.
A PyTorch Tensor is a view over such a Storage that’s capable of indexing into that
storage by using an offset and per-dimension strides.
"""
# points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [15]:
# Figure 2.4 Tensors are views over a Storage instance
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [16]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [18]:
points_storage = points.storage()
points_storage[0]

1.0

In [19]:
points.storage()[1]

4.0

In [22]:
points.storage()[3]

1.0

In [25]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [29]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point

tensor([2., 1.])

In [39]:
# Figure 2.5 Relationship among a tensor’s offset, size, and stride
# The storage offset is the index in the storage that corresponds to the first element in the tensor.
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()
# The resulting tensor has offset 2 in the storage (because we need to skip the first
# point, which has two items) and the size is an instance of the Size class containing
# one element because the tensor is one-dimensional.

2

In [41]:
# The stride is the number of elements in the storage that need to be skipped to obtain the next element along each dimension
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.stride()

(1,)

In [42]:
second_point.size()

torch.Size([2])

In [44]:
second_point.shape

torch.Size([2])

In [45]:
# stride is a tuple indicating the number of elements in the storage that have to be
# skipped when the index is increased by 1 in each dimension
points.stride()

(2, 1)

In [46]:
points.stride(0)

2

In [47]:
points.stride(1)

1

In [50]:
third_point = points[2]
third_point.storage_offset()

4

In [51]:
third_point.stride()

(1,)

In [53]:
third_point.stride(0)

1

In [55]:
third_point.size

<function Tensor.size>

In [56]:
third_point.size()

torch.Size([2])

In [3]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [4]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [5]:
"""
Try transposing now. Take your points tensor, which has individual points in the rows
and x and y coordinates in the columns, and turn it around so that individual points
are along the columns:
"""
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [6]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [7]:
# You can easily verify that the two tensors share storage
id(points.storage()) == id(points_t.storage())

True

In [8]:
points.stride()

(2, 1)

In [9]:
# Figure 2.6 Transpose operation applied to a tensor
points_t.stride()

(1, 2)

In [11]:
"""
Transposing in PyTorch isn’t limited to matrices. You can transpose a multidimensional
array by specifying the two dimensions along which transposing (such as flipping
shape and stride) should occur:
"""
some_tensor = torch.ones(3, 4, 5)
some_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [13]:
some_tensor[(0, 2, 1)]

tensor(1.)

In [14]:
some_tensor[0, 2, 1]

tensor(1.)

In [16]:
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [19]:
some_tensor.shape

torch.Size([3, 4, 5])

In [20]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [21]:
some_tensor_t2 = some_tensor.t()
some_tensor_t2

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

In [22]:
some_tensor.stride()

(20, 5, 1)

In [23]:
some_tensor_t.stride()

(1, 5, 20)

In [24]:
"""
A tensor whose values are laid out in the storage starting from the rightmost dimension
onward (moving along rows for a 2D tensor, for example) is defined as being contiguous.
Contiguous tensors are convenient because you can visit them efficiently and
in order without jumping around in the storage. (Improving data locality improves
performance because of the way memory access works in modern CPUs.)
"""
points.is_contiguous()

True

In [25]:
points_t.is_contiguous()

False

In [28]:
some_tensor.is_contiguous()

True

In [29]:
some_tensor_t.is_contiguous()

False

In [30]:
"""
You can obtain a new contiguous tensor from a noncontiguous one by using the contiguous
method. The content of the tensor stays the same, but the stride changes, as
does the storage:
"""
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [31]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [32]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [34]:
points.stride()

(2, 1)

In [36]:
points_t.stride()

(1, 2)

In [37]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [39]:
points_t_cont.stride()

(3, 1)

In [40]:
"""
Notice that the storage has been reshuffled for elements to be laid out row by row in
the new storage. The stride has been changed to reflect the new layout.
"""
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]