In [1]:
import torch

# Create a tensor of zeros
zeros_tensor = torch.zeros(2, 3)  # 2x3 tensor filled with zeros
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [2]:
# Create a tensor of ones
ones_tensor = torch.ones(2, 3)  # 2x3 tensor filled with ones
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
# Create a tensor with random values
random_tensor = torch.rand(2, 3)  # 2x3 tensor with values uniformly sampled from [0, 1)
random_tensor

tensor([[0.2295, 0.0635, 0.3842],
        [0.5402, 0.0122, 0.2631]])

In [4]:
# Create a tensor with values sampled from a normal distribution
normal_tensor = torch.randn(2, 3)  # 2x3 tensor with values from a standard normal distribution
normal_tensor

tensor([[-0.6882,  0.4430, -1.2973],
        [ 0.8555, -1.2653,  2.5218]])