In [1]:
import torch

# Specify the data type (e.g., float32, int64)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
float_tensor

tensor([1., 2., 3.])

In [2]:
float_tensor.type()

'torch.FloatTensor'

In [3]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
int_tensor

tensor([1, 2, 3])

In [4]:
int_tensor.type()

'torch.LongTensor'

In [5]:
int_tensor2 = torch.tensor([1, 2, 3])
int_tensor2

tensor([1, 2, 3])

In [6]:
int_tensor2.type()

'torch.LongTensor'