In [1]:
import torch

# From a Python list
tensor_from_list = torch.tensor([1, 2, 3])
tensor_from_list

tensor([1, 2, 3])

In [2]:
# From a NumPy array
import numpy as np
numpy_array = np.array([4, 5, 6])
numpy_array

array([4, 5, 6])

In [3]:
tensor_from_numpy = torch.from_numpy(numpy_array)
tensor_from_numpy

tensor([4, 5, 6])